// This file is codegenerated. Run `./database.py --help` for info.
const mkv = @import("../mkv.zig");
const IdInfo = mkv.L2Parser.IdInfo;

pub const database = [_]IdInfo {
    IdInfo { .id=0x1A45DFA3, .type=.master  , .name="EBML"                        },
    IdInfo { .id=0x4286    , .type=.uinteger, .name="EBMLVersion"                 },
    IdInfo { .id=0x42F7    , .type=.uinteger, .name="EBMLReadVersion"             },
    IdInfo { .id=0x42F2    , .type=.string  , .name="EBMLMaxIDLength"             },
    IdInfo { .id=0x42F3    , .type=.uinteger, .name="EBMLMaxSizeLength"           },
    IdInfo { .id=0x4282    , .type=.string  , .name="DocType"                     },
    IdInfo { .id=0x4287    , .type=.uinteger, .name="DocTypeVersion"              },
    IdInfo { .id=0x4285    , .type=.uinteger, .name="DocTypeReadVersion"          },
    IdInfo { .id=0x4281    , .type=.master  , .name="DocTypeExtension"            },
    IdInfo { .id=0x4283    , .type=.string  , .name="DocTypeExtensionName"        },
    IdInfo { .id=0x4284    , .type=.uinteger, .name="DocTypeExtensionVersion"     },
    IdInfo { .id=0xEC      , .type=.binary  , .name="Void"                        },
    IdInfo { .id=0xBF      , .type=.binary  , .name="CRC32"                       },


    IdInfo { .id=0x18538067, .type=.master  , .name="Segment"                     },
    IdInfo { .id=0x114D9B74, .type=.master  , .name="SeekHead"                    },
    IdInfo { .id=0x4DBB    , .type=.master  , .name="Seek"                        },
    IdInfo { .id=0x53AB    , .type=.binary  , .name="SeekID"                      },
    IdInfo { .id=0x53AC    , .type=.uinteger, .name="SeekPosition"                },
    IdInfo { .id=0x1549A966, .type=.master  , .name="Info"                        },
    IdInfo { .id=0x73A4    , .type=.binary  , .name="SegmentUID"                  },
    IdInfo { .id=0x7384    , .type=.utf8    , .name="SegmentFilename"             },
    IdInfo { .id=0x3CB923  , .type=.binary  , .name="PrevUID"                     },
    IdInfo { .id=0x3C83AB  , .type=.utf8    , .name="PrevFilename"                },
    IdInfo { .id=0x3EB923  , .type=.binary  , .name="NextUID"                     },
    IdInfo { .id=0x3E83BB  , .type=.utf8    , .name="NextFilename"                },
    IdInfo { .id=0x4444    , .type=.binary  , .name="SegmentFamily"               },
    IdInfo { .id=0x6924    , .type=.master  , .name="ChapterTranslate"            },
    IdInfo { .id=0x69FC    , .type=.uinteger, .name="ChapterTranslateEditionUID"  },
    IdInfo { .id=0x69BF    , .type=.uinteger, .name="ChapterTranslateCodec"       },
    IdInfo { .id=0x69A5    , .type=.binary  , .name="ChapterTranslateID"          },
    IdInfo { .id=0x2AD7B1  , .type=.uinteger, .name="TimestampScale"              },
    IdInfo { .id=0x4489    , .type=.float   , .name="Duration"                    },
    IdInfo { .id=0x4461    , .type=.date    , .name="DateUTC"                     },
    IdInfo { .id=0x7BA9    , .type=.utf8    , .name="Title"                       },
    IdInfo { .id=0x4D80    , .type=.utf8    , .name="MuxingApp"                   },
    IdInfo { .id=0x5741    , .type=.utf8    , .name="WritingApp"                  },
    IdInfo { .id=0x1F43B675, .type=.master  , .name="Cluster"                     },
    IdInfo { .id=0xE7      , .type=.uinteger, .name="Timestamp"                   },
    IdInfo { .id=0x5854    , .type=.master  , .name="SilentTracks"                },
    IdInfo { .id=0x58D7    , .type=.uinteger, .name="SilentTrackNumber"           },
    IdInfo { .id=0xA7      , .type=.uinteger, .name="Position"                    },
    IdInfo { .id=0xAB      , .type=.uinteger, .name="PrevSize"                    },
    IdInfo { .id=0xA3      , .type=.binary  , .name="SimpleBlock"                 },
    IdInfo { .id=0xA0      , .type=.master  , .name="BlockGroup"                  },
    IdInfo { .id=0xA1      , .type=.binary  , .name="Block"                       },
    IdInfo { .id=0xA2      , .type=.binary  , .name="BlockVirtual"                },
    IdInfo { .id=0x75A1    , .type=.master  , .name="BlockAdditions"              },
    IdInfo { .id=0xA6      , .type=.master  , .name="BlockMore"                   },
    IdInfo { .id=0xEE      , .type=.uinteger, .name="BlockAddID"                  },
    IdInfo { .id=0xA5      , .type=.binary  , .name="BlockAdditional"             },
    IdInfo { .id=0x9B      , .type=.uinteger, .name="BlockDuration"               },
    IdInfo { .id=0xFA      , .type=.uinteger, .name="ReferencePriority"           },
    IdInfo { .id=0xFB      , .type=.integer , .name="ReferenceBlock"              },
    IdInfo { .id=0xFD      , .type=.integer , .name="ReferenceVirtual"            },
    IdInfo { .id=0xA4      , .type=.binary  , .name="CodecState"                  },
    IdInfo { .id=0x75A2    , .type=.integer , .name="DiscardPadding"              },
    IdInfo { .id=0x8E      , .type=.master  , .name="Slices"                      },
    IdInfo { .id=0xE8      , .type=.master  , .name="TimeSlice"                   },
    IdInfo { .id=0xCC      , .type=.uinteger, .name="LaceNumber"                  },
    IdInfo { .id=0xCD      , .type=.uinteger, .name="FrameNumber"                 },
    IdInfo { .id=0xCB      , .type=.uinteger, .name="BlockAdditionID"             },
    IdInfo { .id=0xCE      , .type=.uinteger, .name="Delay"                       },
    IdInfo { .id=0xCF      , .type=.uinteger, .name="SliceDuration"               },
    IdInfo { .id=0xC8      , .type=.master  , .name="ReferenceFrame"              },
    IdInfo { .id=0xC9      , .type=.uinteger, .name="ReferenceOffset"             },
    IdInfo { .id=0xCA      , .type=.uinteger, .name="ReferenceTimestamp"          },
    IdInfo { .id=0xAF      , .type=.binary  , .name="EncryptedBlock"              },
    IdInfo { .id=0x1654AE6B, .type=.master  , .name="Tracks"                      },
    IdInfo { .id=0xAE      , .type=.master  , .name="TrackEntry"                  },
    IdInfo { .id=0xD7      , .type=.uinteger, .name="TrackNumber"                 },
    IdInfo { .id=0x73C5    , .type=.uinteger, .name="TrackUID"                    },
    IdInfo { .id=0x83      , .type=.uinteger, .name="TrackType"                   },
    IdInfo { .id=0xB9      , .type=.uinteger, .name="FlagEnabled"                 },
    IdInfo { .id=0x88      , .type=.uinteger, .name="FlagDefault"                 },
    IdInfo { .id=0x55AA    , .type=.uinteger, .name="FlagForced"                  },
    IdInfo { .id=0x9C      , .type=.uinteger, .name="FlagLacing"                  },
    IdInfo { .id=0x6DE7    , .type=.uinteger, .name="MinCache"                    },
    IdInfo { .id=0x6DF8    , .type=.uinteger, .name="MaxCache"                    },
    IdInfo { .id=0x23E383  , .type=.uinteger, .name="DefaultDuration"             },
    IdInfo { .id=0x234E7A  , .type=.uinteger, .name="DefaultDecodedFieldDuration" },
    IdInfo { .id=0x23314F  , .type=.float   , .name="TrackTimestampScale"         },
    IdInfo { .id=0x537F    , .type=.integer , .name="TrackOffset"                 },
    IdInfo { .id=0x55EE    , .type=.uinteger, .name="MaxBlockAdditionID"          },
    IdInfo { .id=0x536E    , .type=.utf8    , .name="Name"                        },
    IdInfo { .id=0x22B59C  , .type=.string  , .name="Language"                    },
    IdInfo { .id=0x22B59D  , .type=.string  , .name="LanguageIETF"                },
    IdInfo { .id=0x86      , .type=.string  , .name="CodecID"                     },
    IdInfo { .id=0x63A2    , .type=.binary  , .name="CodecPrivate"                },
    IdInfo { .id=0x258688  , .type=.utf8    , .name="CodecName"                   },
    IdInfo { .id=0x7446    , .type=.uinteger, .name="AttachmentLink"              },
    IdInfo { .id=0x3A9697  , .type=.utf8    , .name="CodecSettings"               },
    IdInfo { .id=0x3B4040  , .type=.string  , .name="CodecInfoURL"                },
    IdInfo { .id=0x26B240  , .type=.string  , .name="CodecDownloadURL"            },
    IdInfo { .id=0xAA      , .type=.uinteger, .name="CodecDecodeAll"              },
    IdInfo { .id=0x6FAB    , .type=.uinteger, .name="TrackOverlay"                },
    IdInfo { .id=0x56AA    , .type=.uinteger, .name="CodecDelay"                  },
    IdInfo { .id=0x56BB    , .type=.uinteger, .name="SeekPreRoll"                 },
    IdInfo { .id=0x6624    , .type=.master  , .name="TrackTranslate"              },
    IdInfo { .id=0x66FC    , .type=.uinteger, .name="TrackTranslateEditionUID"    },
    IdInfo { .id=0x66BF    , .type=.uinteger, .name="TrackTranslateCodec"         },
    IdInfo { .id=0x66A5    , .type=.binary  , .name="TrackTranslateTrackID"       },
    IdInfo { .id=0xE0      , .type=.master  , .name="Video"                       },
    IdInfo { .id=0x9A      , .type=.uinteger, .name="FlagInterlaced"              },
    IdInfo { .id=0x9D      , .type=.uinteger, .name="FieldOrder"                  },
    IdInfo { .id=0x53B8    , .type=.uinteger, .name="StereoMode"                  },
    IdInfo { .id=0x53C0    , .type=.uinteger, .name="AlphaMode"                   },
    IdInfo { .id=0x53B9    , .type=.uinteger, .name="OldStereoMode"               },
    IdInfo { .id=0xB0      , .type=.uinteger, .name="PixelWidth"                  },
    IdInfo { .id=0xBA      , .type=.uinteger, .name="PixelHeight"                 },
    IdInfo { .id=0x54AA    , .type=.uinteger, .name="PixelCropBottom"             },
    IdInfo { .id=0x54BB    , .type=.uinteger, .name="PixelCropTop"                },
    IdInfo { .id=0x54CC    , .type=.uinteger, .name="PixelCropLeft"               },
    IdInfo { .id=0x54DD    , .type=.uinteger, .name="PixelCropRight"              },
    IdInfo { .id=0x54B0    , .type=.uinteger, .name="DisplayWidth"                },
    IdInfo { .id=0x54BA    , .type=.uinteger, .name="DisplayHeight"               },
    IdInfo { .id=0x54B2    , .type=.uinteger, .name="DisplayUnit"                 },
    IdInfo { .id=0x54B3    , .type=.uinteger, .name="AspectRatioType"             },
    IdInfo { .id=0x2EB524  , .type=.binary  , .name="ColourSpace"                 },
    IdInfo { .id=0x2FB523  , .type=.float   , .name="GammaValue"                  },
    IdInfo { .id=0x2383E3  , .type=.float   , .name="FrameRate"                   },
    IdInfo { .id=0x55B0    , .type=.master  , .name="Colour"                      },
    IdInfo { .id=0x55B1    , .type=.uinteger, .name="MatrixCoefficients"          },
    IdInfo { .id=0x55B2    , .type=.uinteger, .name="BitsPerChannel"              },
    IdInfo { .id=0x55B3    , .type=.uinteger, .name="ChromaSubsamplingHorz"       },
    IdInfo { .id=0x55B4    , .type=.uinteger, .name="ChromaSubsamplingVert"       },
    IdInfo { .id=0x55B5    , .type=.uinteger, .name="CbSubsamplingHorz"           },
    IdInfo { .id=0x55B6    , .type=.uinteger, .name="CbSubsamplingVert"           },
    IdInfo { .id=0x55B7    , .type=.uinteger, .name="ChromaSitingHorz"            },
    IdInfo { .id=0x55B8    , .type=.uinteger, .name="ChromaSitingVert"            },
    IdInfo { .id=0x55B9    , .type=.uinteger, .name="Range"                       },
    IdInfo { .id=0x55BA    , .type=.uinteger, .name="TransferCharacteristics"     },
    IdInfo { .id=0x55BB    , .type=.uinteger, .name="Primaries"                   },
    IdInfo { .id=0x55BC    , .type=.uinteger, .name="MaxCLL"                      },
    IdInfo { .id=0x55BD    , .type=.uinteger, .name="MaxFALL"                     },
    IdInfo { .id=0x55D0    , .type=.master  , .name="MasteringMetadata"           },
    IdInfo { .id=0x55D1    , .type=.float   , .name="PrimaryRChromaticityX"       },
    IdInfo { .id=0x55D2    , .type=.float   , .name="PrimaryRChromaticityY"       },
    IdInfo { .id=0x55D3    , .type=.float   , .name="PrimaryGChromaticityX"       },
    IdInfo { .id=0x55D4    , .type=.float   , .name="PrimaryGChromaticityY"       },
    IdInfo { .id=0x55D5    , .type=.float   , .name="PrimaryBChromaticityX"       },
    IdInfo { .id=0x55D6    , .type=.float   , .name="PrimaryBChromaticityY"       },
    IdInfo { .id=0x55D7    , .type=.float   , .name="WhitePointChromaticityX"     },
    IdInfo { .id=0x55D8    , .type=.float   , .name="WhitePointChromaticityY"     },
    IdInfo { .id=0x55D9    , .type=.float   , .name="LuminanceMax"                },
    IdInfo { .id=0x55DA    , .type=.float   , .name="LuminanceMin"                },
    IdInfo { .id=0x7670    , .type=.master  , .name="Projection"                  },
    IdInfo { .id=0x7671    , .type=.uinteger, .name="ProjectionType"              },
    IdInfo { .id=0x7672    , .type=.binary  , .name="ProjectionPrivate"           },
    IdInfo { .id=0x7673    , .type=.float   , .name="ProjectionPoseYaw"           },
    IdInfo { .id=0x7674    , .type=.float   , .name="ProjectionPosePitch"         },
    IdInfo { .id=0x7675    , .type=.float   , .name="ProjectionPoseRoll"          },
    IdInfo { .id=0xE1      , .type=.master  , .name="Audio"                       },
    IdInfo { .id=0xB5      , .type=.float   , .name="SamplingFrequency"           },
    IdInfo { .id=0x78B5    , .type=.float   , .name="OutputSamplingFrequency"     },
    IdInfo { .id=0x9F      , .type=.uinteger, .name="Channels"                    },
    IdInfo { .id=0x7D7B    , .type=.binary  , .name="ChannelPositions"            },
    IdInfo { .id=0x6264    , .type=.uinteger, .name="BitDepth"                    },
    IdInfo { .id=0xE2      , .type=.master  , .name="TrackOperation"              },
    IdInfo { .id=0xE3      , .type=.master  , .name="TrackCombinePlanes"          },
    IdInfo { .id=0xE4      , .type=.master  , .name="TrackPlane"                  },
    IdInfo { .id=0xE5      , .type=.uinteger, .name="TrackPlaneUID"               },
    IdInfo { .id=0xE6      , .type=.uinteger, .name="TrackPlaneType"              },
    IdInfo { .id=0xE9      , .type=.master  , .name="TrackJoinBlocks"             },
    IdInfo { .id=0xED      , .type=.uinteger, .name="TrackJoinUID"                },
    IdInfo { .id=0xC0      , .type=.uinteger, .name="TrickTrackUID"               },
    IdInfo { .id=0xC1      , .type=.binary  , .name="TrickTrackSegmentUID"        },
    IdInfo { .id=0xC6      , .type=.uinteger, .name="TrickTrackFlag"              },
    IdInfo { .id=0xC7      , .type=.uinteger, .name="TrickMasterTrackUID"         },
    IdInfo { .id=0xC4      , .type=.binary  , .name="TrickMasterTrackSegmentUID"  },
    IdInfo { .id=0x6D80    , .type=.master  , .name="ContentEncodings"            },
    IdInfo { .id=0x6240    , .type=.master  , .name="ContentEncoding"             },
    IdInfo { .id=0x5031    , .type=.uinteger, .name="ContentEncodingOrder"        },
    IdInfo { .id=0x5032    , .type=.uinteger, .name="ContentEncodingScope"        },
    IdInfo { .id=0x5033    , .type=.uinteger, .name="ContentEncodingType"         },
    IdInfo { .id=0x5034    , .type=.master  , .name="ContentCompression"          },
    IdInfo { .id=0x4254    , .type=.uinteger, .name="ContentCompAlgo"             },
    IdInfo { .id=0x4255    , .type=.binary  , .name="ContentCompSettings"         },
    IdInfo { .id=0x5035    , .type=.master  , .name="ContentEncryption"           },
    IdInfo { .id=0x47E1    , .type=.uinteger, .name="ContentEncAlgo"              },
    IdInfo { .id=0x47E2    , .type=.binary  , .name="ContentEncKeyID"             },
    IdInfo { .id=0x47E7    , .type=.master  , .name="ContentEncAESSettings"       },
    IdInfo { .id=0x47E8    , .type=.uinteger, .name="AESSettingsCipherMode"       },
    IdInfo { .id=0x47E3    , .type=.binary  , .name="ContentSignature"            },
    IdInfo { .id=0x47E4    , .type=.binary  , .name="ContentSigKeyID"             },
    IdInfo { .id=0x47E5    , .type=.uinteger, .name="ContentSigAlgo"              },
    IdInfo { .id=0x47E6    , .type=.uinteger, .name="ContentSigHashAlgo"          },
    IdInfo { .id=0x1C53BB6B, .type=.master  , .name="Cues"                        },
    IdInfo { .id=0xBB      , .type=.master  , .name="CuePoint"                    },
    IdInfo { .id=0xB3      , .type=.uinteger, .name="CueTime"                     },
    IdInfo { .id=0xB7      , .type=.master  , .name="CueTrackPositions"           },
    IdInfo { .id=0xF7      , .type=.uinteger, .name="CueTrack"                    },
    IdInfo { .id=0xF1      , .type=.uinteger, .name="CueClusterPosition"          },
    IdInfo { .id=0xF0      , .type=.uinteger, .name="CueRelativePosition"         },
    IdInfo { .id=0xB2      , .type=.uinteger, .name="CueDuration"                 },
    IdInfo { .id=0x5378    , .type=.uinteger, .name="CueBlockNumber"              },
    IdInfo { .id=0xEA      , .type=.uinteger, .name="CueCodecState"               },
    IdInfo { .id=0xDB      , .type=.master  , .name="CueReference"                },
    IdInfo { .id=0x96      , .type=.uinteger, .name="CueRefTime"                  },
    IdInfo { .id=0x97      , .type=.uinteger, .name="CueRefCluster"               },
    IdInfo { .id=0x535F    , .type=.uinteger, .name="CueRefNumber"                },
    IdInfo { .id=0xEB      , .type=.uinteger, .name="CueRefCodecState"            },
    IdInfo { .id=0x1941A469, .type=.master  , .name="Attachments"                 },
    IdInfo { .id=0x61A7    , .type=.master  , .name="AttachedFile"                },
    IdInfo { .id=0x467E    , .type=.utf8    , .name="FileDescription"             },
    IdInfo { .id=0x466E    , .type=.utf8    , .name="FileName"                    },
    IdInfo { .id=0x4660    , .type=.string  , .name="FileMimeType"                },
    IdInfo { .id=0x465C    , .type=.binary  , .name="FileData"                    },
    IdInfo { .id=0x46AE    , .type=.uinteger, .name="FileUID"                     },
    IdInfo { .id=0x4675    , .type=.binary  , .name="FileReferral"                },
    IdInfo { .id=0x4661    , .type=.uinteger, .name="FileUsedStartTime"           },
    IdInfo { .id=0x4662    , .type=.uinteger, .name="FileUsedEndTime"             },
    IdInfo { .id=0x1043A770, .type=.master  , .name="Chapters"                    },
    IdInfo { .id=0x45B9    , .type=.master  , .name="EditionEntry"                },
    IdInfo { .id=0x45BC    , .type=.uinteger, .name="EditionUID"                  },
    IdInfo { .id=0x45BD    , .type=.uinteger, .name="EditionFlagHidden"           },
    IdInfo { .id=0x45DB    , .type=.uinteger, .name="EditionFlagDefault"          },
    IdInfo { .id=0x45DD    , .type=.uinteger, .name="EditionFlagOrdered"          },
    IdInfo { .id=0xB6      , .type=.master  , .name="ChapterAtom"                 },
    IdInfo { .id=0x73C4    , .type=.uinteger, .name="ChapterUID"                  },
    IdInfo { .id=0x5654    , .type=.utf8    , .name="ChapterStringUID"            },
    IdInfo { .id=0x91      , .type=.uinteger, .name="ChapterTimeStart"            },
    IdInfo { .id=0x92      , .type=.uinteger, .name="ChapterTimeEnd"              },
    IdInfo { .id=0x98      , .type=.uinteger, .name="ChapterFlagHidden"           },
    IdInfo { .id=0x4598    , .type=.uinteger, .name="ChapterFlagEnabled"          },
    IdInfo { .id=0x6E67    , .type=.binary  , .name="ChapterSegmentUID"           },
    IdInfo { .id=0x6EBC    , .type=.uinteger, .name="ChapterSegmentEditionUID"    },
    IdInfo { .id=0x63C3    , .type=.uinteger, .name="ChapterPhysicalEquiv"        },
    IdInfo { .id=0x8F      , .type=.master  , .name="ChapterTrack"                },
    IdInfo { .id=0x89      , .type=.uinteger, .name="ChapterTrackUID"             },
    IdInfo { .id=0x80      , .type=.master  , .name="ChapterDisplay"              },
    IdInfo { .id=0x85      , .type=.utf8    , .name="ChapString"                  },
    IdInfo { .id=0x437C    , .type=.string  , .name="ChapLanguage"                },
    IdInfo { .id=0x437D    , .type=.string  , .name="ChapLanguageIETF"            },
    IdInfo { .id=0x437E    , .type=.string  , .name="ChapCountry"                 },
    IdInfo { .id=0x6944    , .type=.master  , .name="ChapProcess"                 },
    IdInfo { .id=0x6955    , .type=.uinteger, .name="ChapProcessCodecID"          },
    IdInfo { .id=0x450D    , .type=.binary  , .name="ChapProcessPrivate"          },
    IdInfo { .id=0x6911    , .type=.master  , .name="ChapProcessCommand"          },
    IdInfo { .id=0x6922    , .type=.uinteger, .name="ChapProcessTime"             },
    IdInfo { .id=0x6933    , .type=.binary  , .name="ChapProcessData"             },
    IdInfo { .id=0x1254C367, .type=.master  , .name="Tags"                        },
    IdInfo { .id=0x7373    , .type=.master  , .name="Tag"                         },
    IdInfo { .id=0x63C0    , .type=.master  , .name="Targets"                     },
    IdInfo { .id=0x68CA    , .type=.uinteger, .name="TargetTypeValue"             },
    IdInfo { .id=0x63CA    , .type=.string  , .name="TargetType"                  },
    IdInfo { .id=0x63C5    , .type=.uinteger, .name="TagTrackUID"                 },
    IdInfo { .id=0x63C9    , .type=.uinteger, .name="TagEditionUID"               },
    IdInfo { .id=0x63C4    , .type=.uinteger, .name="TagChapterUID"               },
    IdInfo { .id=0x63C6    , .type=.uinteger, .name="TagAttachmentUID"            },
    IdInfo { .id=0x67C8    , .type=.master  , .name="SimpleTag"                   },
    IdInfo { .id=0x45A3    , .type=.utf8    , .name="TagName"                     },
    IdInfo { .id=0x447A    , .type=.string  , .name="TagLanguage"                 },
    IdInfo { .id=0x447B    , .type=.string  , .name="TagLanguageIETF"             },
    IdInfo { .id=0x4484    , .type=.uinteger, .name="TagDefault"                  },
    IdInfo { .id=0x4487    , .type=.utf8    , .name="TagString"                   },
    IdInfo { .id=0x4485    , .type=.binary  , .name="TagBinary"                   },

};

